language: java
jdk:
- openjdk8
dist: bionic
before_install:
- openssl aes-256-cbc -K $encrypted_7c6b24e34caf_key -iv $encrypted_7c6b24e34caf_iv -in travis/pubring.gpg.enc -out travis/pubring.gpg -d
- openssl aes-256-cbc -K $encrypted_6afd0fc9428e_key -iv $encrypted_6afd0fc9428e_iv -in travis/secring.gpg.enc -out travis/secring.gpg -d
script:
- mvn verify
after_success:
- mvn coveralls:report
- test "${TRAVIS_PULL_REQUEST}" == "false" && test "${TRAVIS_TAG}" != "" && mvn deploy --settings travis/settings.xml -DskipTests=true -Prelease
cache:
  directories:
  - "~/.m2"
branches:
  only:
  - master
  - "/^bullet-record-[0-9]+\\.[0-9]+\\.[0-9]+/"
env:
  global:
  - GPG_EXECUTABLE=gpg
  - secure: HVp1b2G0JFUeU0sJsotJmiGKuA4ERPO9k2VPlAxEskfsBimhirIQaIWuU2JnUDrsA2dR5kSYF7mrNY/CoyXv3f1oFlh4r2+qbqmPiXtFAxECwZgDgtk0wu+oXJQDVkDzG9GsnRT/UG5sGkg3zj+eJsnGBBeuRl0NmE4D+UaRUTKTYhGE0DeCi5QoBEH3py8YfHpL080zdEZoq4rWRlJMejzDffFbhfqVjf/EFnef/dV8ednp0qcmO1ksVmLFkc2iSXNCjmBWpgfYvEfiNXaxwRraPrv5wj5t1zlZiujZ2sKiGy4YWiGmYAQAc5o0oiZGz6B6w0yXuG9P/KTO0OXXen9ndSyKKm7PinOzGelW/8lHucDu5aGamZaBIYUcc4hpq6NQYNDURFo9uC0KaONXN7Uz7phofeuUf5j6FHQy4ZI6bQx0plYOiAL2Dxcazy0Z0DDBIbzQy+A2onbfX5/Cu9JIDHis82bVM3kg9wbmPWERpzLMXEq6esU74Fbo9/wy6qN0Q8CZ+7eSMGUqNRuY0NbjUQmehN7r4tYNXGm0PVuDLaqZhm9d+NmDxlbs8y4CK1JcKnWgxFy7S7DpiENOZ8tBs9sSyxFaribqzx7v6JCV8D55VWwOgE9jdG+4RsYe5/pALTANZutnKQF75YE1UIUQL9WNd5e458MuNv2+cw8=
  - secure: WKYZe8ozcrCbcx8iVVIbttgDemo9AYPBsxMxB3kigYs/KvYcAM+r9C+xD9bYJkE0J86Ft3D9oqFaK6ii5luxzIhZmkJsdI1mrkykbK45WhdUd6aVUNLAWZ1IlWen+y1pL4IXepIako9eVC5BbmrZds8DRcEtz5lFhWt7pEEPDGFXgCZpM/Y0J679z85hAuY86Z/rx0+256wb1hCFEvsAYg6QS2v4boMQjYHRhlONf7vNZdRMmSqGP4sUQs0rTzPRP5+jUIYlDxy131+WHKlSSpUp/4XraRn8LUfv10RK/FjPj0H77to5fe4BsvXmnvLWB+qb1RYUNcLzJW4+hhGYmOk6Yrtl4Vc821K6MuqRev1x97vVD/5RPlIz3ti1BeUKxxj1QZZ+fAannWyymWRfsqKyuH7l0kGnptM6N/cOo01k+SLCSAyLMvjIfsCL/c7Zk/6l4s0cSi9v7VoShgnWDGAWkOEqVrXHrR2AF1VhyNHBJKwJdn1MuQxrQkoS0ah76gIqfEBvs3Wsc8giYJWGhoolqrTDUwyx+Wt9k0AkpnmmdxBqGUWGc7MHlZNsd4pM7SvsHFB/Oqx9PPkLPqDBGGcMtyIVB49JTPexPIJvj2lMlW1ec2d+x/sWpJaNKGzpoPkd+e1Edr1fu7hQDk6eMa9VOL+mjxY5KYdudq+nZ/0=
  - secure: Rg8MMeVBlwbYeBvKG2qpedoHwHfPyyQOQSYwWcNllkDhje6ORh6hd7QLXqI2i56847VUETiPPik7olz91SF5IAtPxwlgAglCHjWPoDhMFpMBcQ/tyfpVvWjuqoyKRSRE0795oTwp9T3TTzqKtZobqI5tH0Hy7Bh9J97wGcabYQFudahxDAE7H2SPhT9N1fSYZCzjYDZZO52J6c6lwkPhL7uW1/Wen+HGse8wZBGWIraXek3dMDwmZQTELTuJNlrZDkrlGnbgM6Zz64koxmnT+eGY6sdu30/gHzMwTnoEDBDjIowZaaKMG/S4UlpLBR21EmbgS8nphs2mmTVR/ILj3IKYBd4h65aYCqfuV4iYjn5XK/wn7E13aY4PcMOGaw30vesvXEgLcr5smgPyttNm2GnY1eThBiAeZlt6oafGhpfrNO3CdoAKAW0eNSO/BQrh2v6l5KZmd1AB5TPZair4cijWUYDlx/zw/TAHsydEmbMofLuOhWIr6bC5qBnQTtLKQqkMRA/T/3lzPmEgCTX+5ASvBr0VUEPRc/f5yE4Bo8dtsVLXlW/ngIAM1zm27/4jRMolEotBYZQ+NfSwTzv21y/f6//mhR+Kkd6V8vpfiQxD+L6C2+d4Xj9ljF56iliLKWGujl/twHYSTT+Gm2H7AFc3qIV7kJWfn/91H81a4WY=
